version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/source"
    schedule:
      interval: "cron"
      cron: "0 11 * * 1"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps: "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cron: "0 11 * * 1"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "[gh-actions]: "

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "cron"
      cron: "0 11 * * 1"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "[dockerfile]: "
